--Name: Jian Shi--
--USCID: 7983158453--

DROP INDEX regionindex;

DROP INDEX lionindex;
   
DROP INDEX pondindex;

DROP INDEX ambulanceindex;

DELETE FROM  USER_SDO_GEOM_METADATA WHERE TABLE_NAME='REGION';

DELETE FROM  USER_SDO_GEOM_METADATA WHERE TABLE_NAME='LION';

DELETE FROM  USER_SDO_GEOM_METADATA WHERE TABLE_NAME='POND';

DELETE FROM  USER_SDO_GEOM_METADATA WHERE TABLE_NAME='AMBULANCEAREA';

DROP TABLE region;

DROP TABLE lion;

DROP TABLE pond;

DROP TABLE ambulancearea;